name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/design/images/frame-3649.png
    - assets/design/images/frame-3650.png
    - assets/design/images/rectangle-6.png
    - assets/design/images/group-3647.png
    - assets/design/images/frame-108.png
    - assets/design/images/rectangle-11.png
    - assets/design/images/group-9.png
    - assets/design/images/frame-3653.png
    - assets/design/images/frame-108-aZF.png
    - assets/design/images/group-8.png
    - assets/design/images/edit.png
    - assets/design/images/group-26.png
    - assets/design/images/frame-3653-3Ay.png
    - assets/design/images/frame-3679.png
    - assets/design/images/group-70.png
    - assets/design/images/group-70-Adw.png
    - assets/design/images/rectangle-26.png
    - assets/design/images/untitled-1-1.png
    - assets/design/images/new.png
    - assets/design/images/vector.png
    - assets/design/images/image-80-traced.png
    - assets/design/images/rectangle-28.png
    - assets/design/images/group-1333.png
    - assets/design/images/baby.png
    - assets/design/images/new-NMF.png
    - assets/design/images/auto-group-92s9.png
    - assets/design/images/frame-3679-53o.png
    - assets/design/images/auto-group-syp5.png
    - assets/design/images/group-985.png
    - assets/design/images/ellipse-1-bg.png
    - assets/design/images/rectangle-11-3rq.png
    - assets/design/images/coco-bold-star.png
    - assets/design/images/coco-bold-star-dtu.png
    - assets/design/images/group-956.png
    - assets/design/images/mask-group.png
    - assets/design/images/instagram.png
    - assets/design/images/calender.png
    - assets/design/images/coco-duotone-arrow-left.png
    - assets/design/images/vector-gLR.png
    - assets/design/images/group-1330.png
    - assets/design/images/frame-3653-UCy.png
    - assets/design/images/coco-line-clock.png
    - assets/design/images/frame-3679-eaV.png
    - assets/design/images/coco-bold-star-ZPF.png
    - assets/design/images/frame-3653-xtZ.png
    - assets/design/images/coco-line-clock-oTF.png
    - assets/design/images/line-23.png
    - assets/design/images/vector-imF.png
    - assets/design/images/image-72.png
    - assets/design/images/facebook.png
    - assets/design/images/frame-3653-o1s.png
    - assets/design/images/frame-3679-iDw.png
    - assets/design/images/frame-3679-ETB.png
    - assets/design/images/frame-3679-6Vw.png
    - assets/design/images/coco-line-cup.png
    - assets/design/images/coco-bold-star-z7B.png
    - assets/design/images/group-1349.png
    - assets/design/images/coco-line-more.png
    - assets/design/images/coco-line-clock-7Wy.png
    - assets/design/images/group-956-wey.png
    - assets/design/images/coco-bold-star-JAd.png
    - assets/design/images/frame-3653-uww.png
    - assets/design/images/coco-duotone-arrow-left-8SV.png
    - assets/design/images/frame-3679-ddK.png
    - assets/design/images/coco-bold-star-ekR.png
    - assets/design/images/coco-bold-star-z3b.png
    - assets/design/images/coco-bold-star-1FF.png
    - assets/design/images/coco-bold-star-2ED.png
    - assets/design/images/search.png
    - assets/design/images/auto-group-4vub.png
    - assets/design/images/frame-3653-KPw.png
    - assets/design/images/frame-3679-ezV.png
    - assets/design/images/subtract.png
    - assets/design/images/coco-bold-star-8hX.png
    - assets/design/images/calender-zQH.png
    - assets/design/images/coco-bold-star-xNM.png
    - assets/design/images/image-2.png
    - assets/design/images/husband-nevbar.png
    - assets/design/images/frame-3679-Vxm.png
    - assets/design/images/group-1020.png
    - assets/design/images/frame-3653-RvZ.png
    - assets/design/images/coco-bold-star-mo7.png
    - assets/design/images/search-uTP.png
    - assets/design/images/search-mvq.png
    - assets/design/images/coco-line-cup-MFo.png
    - assets/design/images/coco-bold-star-yny.png
    - assets/design/images/coco-line-more-J4Z.png
    - assets/design/images/group-985-e1w.png
    - assets/design/images/frame-3679-BnZ.png
    - assets/design/images/coco-bold-star-Q33.png
    - assets/design/images/coco-bold-star-Anu.png
    - assets/design/images/image-80-traced-aNm.png
    - assets/design/images/coco-duotone-arrow-left-r65.png
    - assets/design/images/image-76.png
    - assets/design/images/coco-duotone-arrow-left-cKT.png
    - assets/design/images/group.png
    - assets/design/images/ellipse-12-bg.png
    - assets/design/images/mask-group-a6D.png
    - assets/design/images/frame-3653-xZf.png
    - assets/design/images/twitter.png
    - assets/design/images/pic-3-1.png
    - assets/design/images/pic-1-1.png
    - assets/design/images/frame-3653-ADo.png
    - assets/design/images/image-77.png
    - assets/design/images/mask-group-i2m.png
    - assets/design/images/mask-group-J6M.png
    - assets/design/images/pic-2-1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
